print("PERSEGI")
sisi= int(input("masukan sisi:"))
print("PERSEGI PANJANG")
panjang=int(input("masukan panjang:"))
lebar= int(input("masukan lebar:"))
print("TRAPESIUM")
ab=int(input("masukkan ab:"))
bc=int(input("masukkan bc:"))
cd=int(input("masukkan cd:"))
da=int(input("masukkan ad:"))
tinggi= int(input("masukkan tinggi:"))
print("luas persegi adalah:",sisi*sisi)
print("keliling persegi adalah:",sisi," ADALAH:", sisi * 4 )
print("luas persegi panjang adalah:",panjang*lebar)
print("keliling persegi panjang adalah:",2*(panjang+lebar))
print("luas trapesium adalah:",tinggi/2*(ab+cd))
print("keliling trapesium adalah:",ab+bc+cd+da)
